# Generated by Django 3.0.7 on 2020-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200611_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='email_prefix',
            field=models.CharField(max_length=255, verbose_name='email suffix'),
        ),
    ]
