version: "3.0"
services:
  backend:
    build: ./backend
    ports:
      - "3600:8000"
    command: bash -c "chmod +x ./youngun/docker-entrypoint.sh && sh ./youngun/docker-entrypoint.sh"
    # volumes:
    #   - ./backend/youngun:/code

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3500:80"
    environment:
      - REACT_APP_BACKENDURL=https://trackingapi.youngun.in/
