version: "3.0"
services:
  backend:
    build: ./backend
    ports:
      - "3600:8000"
    # volumes:
    #   - ./backend/youngun:/code
    
    command: bash -c "chmod +x ./youngun/docker-entrypoint.sh && sh ./youngun/docker-entrypoint.sh"
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3500:80"
