# Generated by Django 3.0.7 on 2020-06-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='brand',
        ),
    ]
