# Generated by Django 3.0.7 on 2020-06-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usermanager.profile',),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usermanager.profile',),
        ),
        migrations.RemoveField(
            model_name='brand',
            name='organisation',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_client_profile',
            field=models.BooleanField(default=True, verbose_name='Is Client Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_staff_profile',
            field=models.BooleanField(default=False, verbose_name='Is Staff Profile'),
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
