# Generated by Django 3.0.7 on 2020-07-04 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20200703_1702'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanager', '0003_remove_profile_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Last Name')),
                ('is_main_user', models.BooleanField(default=False, verbose_name='Main User')),
                ('added_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invited_users', to='usermanager.ClientProfile', verbose_name='Added By')),
                ('campaigns', models.ManyToManyField(blank=True, related_name='client_profiles', to='campaigns.Campaign', verbose_name='campaigns')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usermanager_clientprofile', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Last Name')),
                ('campaigns', models.ManyToManyField(blank=True, related_name='staff_profiles', to='campaigns.Campaign', verbose_name='campaigns')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usermanager_staffprofile', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
