# Generated by Django 3.0.7 on 2020-07-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200704_1019'),
        ('usermanager', '0005_userproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProxy',
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
    ]
