# Generated by Django 3.0.7 on 2020-07-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0007_staffprofile_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='usermanager.Brand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='usermanager.Brand', verbose_name='Brand'),
        ),
    ]
