# Generated by Django 3.0.8 on 2020-07-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200704_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authInProgress',
            field=models.BooleanField(blank=True, default=False, verbose_name='AuthInProgress'),
        ),
        migrations.AddField(
            model_name='user',
            name='tempid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TempID'),
        ),
        migrations.AddField(
            model_name='user',
            name='tempotp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TempOTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
    ]
