# Generated by Django 3.0.8 on 2020-07-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200724_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_requested',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last OTP Request'),
        ),
    ]
