# Generated by Django 3.0.8 on 2020-08-18 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('login_cnt', models.IntegerField(default=0, verbose_name='Total Login Count')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('history_log', models.TextField(verbose_name='Login History')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterlogger', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
