# Generated by Django 3.0.7 on 2020-06-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='post url')),
                ('platform', models.CharField(choices=[('in', 'Instagram'), ('fb', 'Facebook'), ('tw', 'Twitter')], max_length=50, verbose_name='platform')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('comments', models.IntegerField(default=0, verbose_name='comments')),
                ('post_shares', models.IntegerField(default=0, verbose_name='post_shares')),
                ('post_saves', models.IntegerField(default=0, verbose_name='post_saves')),
                ('post_reach', models.IntegerField(default=0, verbose_name='post_reach')),
                ('date', models.DateTimeField(verbose_name='posted date')),
                ('embed_code', models.TextField(null=True, verbose_name='embed code')),
                ('post_type', models.CharField(choices=[('p', 'post'), ('v', 'video')], max_length=50, null=True, verbose_name='post_type')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.post',),
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.post',),
        ),
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.post',),
        ),
    ]
