# Generated by Django 3.0.7 on 2020-06-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', verbose_name='Story Snapshot URL')),
                ('platform', models.CharField(choices=[('fb', 'Facebook'), ('in', 'Instagram'), ('tw', 'Twitter')], default='in', max_length=50, verbose_name='platform')),
                ('story_views', models.IntegerField(default=0, verbose_name='Story Views')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='posted timestamp')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='campaigns.Campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name_plural': 'All Stories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='post url')),
                ('platform', models.CharField(choices=[('fb', 'Facebook'), ('in', 'Instagram'), ('tw', 'Twitter')], max_length=50, verbose_name='platform')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('comments', models.IntegerField(default=0, verbose_name='comments')),
                ('post_shares', models.IntegerField(default=0, verbose_name='post_shares')),
                ('post_saves', models.IntegerField(default=0, verbose_name='post_saves')),
                ('post_reach', models.IntegerField(default=0, verbose_name='post_reach')),
                ('date', models.DateField(auto_now_add=True, verbose_name='posted date')),
                ('embed_code', models.TextField(blank=True, null=True, verbose_name='embed code')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50, verbose_name='post visibility')),
                ('post_type', models.CharField(blank=True, choices=[('p', 'Post'), ('v', 'Video')], max_length=50, null=True, verbose_name='post_type')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='campaigns.Campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name_plural': 'All Posts',
            },
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.post',),
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.post',),
        ),
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.post',),
        ),
    ]
