# Generated by Django 3.0.7 on 2020-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_google_photo_url',
            field=models.URLField(blank=True, default='example.com', max_length=400, null=True, verbose_name='Alternate Google Photo URL'),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(default='example.com', verbose_name='Story Snapshot URL'),
        ),
    ]
