# Generated by Django 3.0.7 on 2020-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('fb', 'Facebook'), ('in', 'Instagram'), ('tw', 'Twitter')], max_length=50, verbose_name='platform'),
        ),
    ]
