# Generated by Django 3.0.7 on 2020-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200611_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='posted date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='embed_code',
            field=models.TextField(blank=True, null=True, verbose_name='embed code'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('p', 'post'), ('v', 'video')], max_length=50, null=True, verbose_name='post_type'),
        ),
    ]
