# Generated by Django 3.0.7 on 2020-07-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_facebookstory_instagramstory_twitterstory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookpost',
            options={'verbose_name_plural': 'Facebook Posts'},
        ),
        migrations.AlterModelOptions(
            name='facebookstory',
            options={'verbose_name_plural': 'Facebook Stories'},
        ),
        migrations.AlterModelOptions(
            name='instagrampost',
            options={'verbose_name_plural': 'Instagram Posts'},
        ),
        migrations.AlterModelOptions(
            name='instagramstory',
            options={'verbose_name_plural': 'Instagram Stories'},
        ),
        migrations.AlterModelOptions(
            name='twitterpost',
            options={'verbose_name_plural': 'Twitter Posts'},
        ),
        migrations.AlterModelOptions(
            name='twitterstory',
            options={'verbose_name_plural': 'Twitter Stories'},
        ),
    ]
