# Generated by Django 3.0.7 on 2020-06-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20200611_1800'),
        ('content', '0004_auto_20200612_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign', verbose_name='campaign'),
        ),
    ]
