# Generated by Django 3.0.8 on 2020-07-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200703_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='alt_google_photo_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Alternate Google Photo URL'),
        ),
    ]
