# Generated by Django 3.0.8 on 2020-08-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200801_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Upload Username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='alt_google_photo_url',
            field=models.URLField(blank=True, max_length=1500, null=True, verbose_name='Alternate Google Photo URL'),
        ),
    ]
