# Generated by Django 3.0.3 on 2020-09-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20200819_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Name'),
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Post Caption'),
        ),
        migrations.AddField(
            model_name='post',
            name='social_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Post Social ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Upload DateTime'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Media Key')),
                ('url', models.URLField(max_length=2000, verbose_name='Media URL')),
                ('media_type', models.CharField(choices=[('post', 'Post'), ('video', 'Video')], max_length=50, verbose_name='Media Type')),
                ('parent_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='content.Post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media Objects',
            },
        ),
    ]
