# Generated by Django 3.0.3 on 2020-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20200914_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_views',
            field=models.IntegerField(default=0, verbose_name='Media Views'),
        ),
        migrations.AddField(
            model_name='post',
            name='alive',
            field=models.BooleanField(default=True, verbose_name='Post Health'),
        ),
    ]
