# Generated by Django 3.0.7 on 2020-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20200627_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.URLField(default='', verbose_name='Story Snapshot URL'),
        ),
        migrations.AlterField(
            model_name='story',
            name='platform',
            field=models.CharField(choices=[('fb', 'Facebook'), ('in', 'Instagram'), ('tw', 'Twitter')], default='in', max_length=50, verbose_name='platform'),
        ),
    ]
