# Generated by Django 3.0.3 on 2020-09-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20200914_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pre_fetched',
            field=models.BooleanField(default=False, verbose_name='Data Pre Fetched'),
        ),
    ]
