# Generated by Django 3.0.3 on 2020-10-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_post_pre_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='alt_google_photo_url',
            field=models.URLField(blank=True, max_length=8000, null=True, verbose_name='Alternate Google Photo URL'),
        ),
    ]
