# Generated by Django 3.0.3 on 2020-10-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20201002_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_engagement',
            field=models.IntegerField(default=0, verbose_name='post_engagement'),
        ),
    ]
