# Generated by Django 3.0.3 on 2021-01-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20201102_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prof_img_url',
            field=models.URLField(default='', max_length=2000, verbose_name='profile image url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=2000, unique=True, verbose_name='post url'),
        ),
    ]
