# Generated by Django 3.0.3 on 2021-01-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20210110_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prof_img_url',
            field=models.URLField(blank=True, default='', max_length=2000, null=True, verbose_name='profile image url'),
        ),
    ]
