# Generated by Django 3.0.3 on 2021-01-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20210111_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Upload DateTime'),
        ),
    ]
