# Generated by Django 3.0.7 on 2020-07-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('hashtag', models.CharField(max_length=100, verbose_name='Hashtag')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=50, verbose_name='Campaign Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Campaign Start')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Campaign End')),
                ('slide_url', models.URLField(default='example.com', verbose_name='Slide URL')),
                ('live_google_sheet', models.URLField(default='example.com', verbose_name='Live Google Sheet')),
                ('reports_google_sheet', models.URLField(default='example.com', verbose_name='Reports Google Sheet')),
                ('slug', models.SlugField(blank=True, verbose_name='Slug')),
                ('particaipating_profiles', models.IntegerField(default=0, verbose_name='particaipating profiles')),
                ('unique_content_pieces', models.IntegerField(default=0, verbose_name='unique content pieces')),
                ('approved_content_pieces', models.IntegerField(default=0, verbose_name='approved content pieces')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('fb_posts', models.IntegerField(default=0, verbose_name='facebook posts')),
                ('fb_stories', models.IntegerField(default=0, verbose_name='facebook stories')),
                ('in_posts', models.IntegerField(default=0, verbose_name='instagram posts')),
                ('in_stories', models.IntegerField(default=0, verbose_name='instagram stories')),
                ('tw_posts', models.IntegerField(default=0, verbose_name='twitter posts')),
                ('tw_stories', models.IntegerField(default=0, verbose_name='twitter stories')),
                ('live_fb_posts', models.IntegerField(default=0, verbose_name='live facebook posts')),
                ('live_fb_stories', models.IntegerField(default=0, verbose_name='live facebook stories')),
                ('live_in_posts', models.IntegerField(default=0, verbose_name='live instagram posts')),
                ('live_in_stories', models.IntegerField(default=0, verbose_name='live instagram stories')),
                ('live_tw_posts', models.IntegerField(default=0, verbose_name='live twitter posts')),
                ('live_tw_stories', models.IntegerField(default=0, verbose_name='live twitter stories')),
                ('stories_google_photos_album_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Stories Album URL')),
                ('stories_fetch_ctrl', models.BooleanField(default=False, verbose_name='Stories fetched?')),
                ('num_content_pieces', models.IntegerField(default=0, verbose_name='num content pieces')),
                ('num_posts', models.IntegerField(default=0, verbose_name='num posts')),
                ('num_stories', models.IntegerField(default=0, verbose_name='num stories')),
                ('post_stats', models.IntegerField(default=0, verbose_name='post stats')),
                ('post_shares', models.IntegerField(default=0, verbose_name='post shares')),
                ('post_saves', models.IntegerField(default=0, verbose_name='post saves')),
                ('post_reach', models.IntegerField(default=0, verbose_name='post reach')),
                ('story_views', models.IntegerField(default=0, verbose_name='story views')),
                ('website_traffic', models.IntegerField(default=0, verbose_name='website traffic')),
                ('cost_per_engagement', models.CharField(blank=True, max_length=50, verbose_name='cost per engagement')),
                ('cost_per_post_impression', models.CharField(blank=True, max_length=50, verbose_name='cost per post impression')),
                ('total_post_engagement', models.CharField(blank=True, max_length=50, verbose_name='total post engagement')),
                ('total_campaign_reach', models.CharField(blank=True, max_length=50, verbose_name='total campaign reach')),
            ],
            options={
                'verbose_name_plural': 'All Campaigns',
            },
        ),
    ]
