# Generated by Django 3.0.7 on 2020-06-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20200611_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('hashtag', models.CharField(max_length=100, verbose_name='Hashtag')),
                ('num_content_pieces', models.IntegerField(default=0, verbose_name='num content pieces')),
                ('num_posts', models.IntegerField(default=0, verbose_name='num posts')),
                ('num_stories', models.IntegerField(default=0, verbose_name='num stories')),
                ('post_stats', models.IntegerField(default=0, verbose_name='post stats')),
                ('post_shares', models.IntegerField(default=0, verbose_name='post shares')),
                ('post_saves', models.IntegerField(default=0, verbose_name='post saves')),
                ('post_reach', models.IntegerField(default=0, verbose_name='post reach')),
                ('story_views', models.IntegerField(default=0, verbose_name='story views')),
                ('website_traffic', models.IntegerField(default=0, verbose_name='website traffic')),
                ('cost_per_engagement', models.CharField(max_length=50, verbose_name='cost per engagement')),
                ('cost_per_post_impression', models.CharField(max_length=50, verbose_name='cost per post impression')),
                ('total_post_engagement', models.CharField(max_length=50, verbose_name='total post engagement')),
                ('total_campaign_reach', models.CharField(max_length=50, verbose_name='total campaign reach')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Organisation', verbose_name='organisation')),
            ],
        ),
    ]
