# Generated by Django 3.0.7 on 2020-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cost_per_engagement',
            field=models.CharField(blank=True, max_length=50, verbose_name='cost per engagement'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cost_per_post_impression',
            field=models.CharField(blank=True, max_length=50, verbose_name='cost per post impression'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_campaign_reach',
            field=models.CharField(blank=True, max_length=50, verbose_name='total campaign reach'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_post_engagement',
            field=models.CharField(blank=True, max_length=50, verbose_name='total post engagement'),
        ),
    ]
