# Generated by Django 3.0.7 on 2020-06-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name_plural': 'All Campaigns'},
        ),
    ]
