# Generated by Django 3.0.7 on 2020-06-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200613_0659'),
        ('campaigns', '0002_auto_20200613_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='authentication.Organisation', verbose_name='Organisation'),
        ),
    ]
