# Generated by Django 3.0.7 on 2020-06-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20200628_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='stories_google_photos_album_url',
            field=models.URLField(blank=True, default='example.com', max_length=500, verbose_name='Stories Album URL'),
        ),
    ]
