# Generated by Django 3.0.7 on 2020-06-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20200627_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='stories_google_photos_album_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Stories Album URL'),
        ),
    ]
