# Generated by Django 3.0.7 on 2020-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20200701_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='stories_google_photos_album_url',
        ),
        migrations.AddField(
            model_name='campaign',
            name='fb_stories_google_photos_album_url',
            field=models.URLField(blank=True, default='example.com', max_length=500, verbose_name='Facebook Stories Album URL'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='in_stories_google_photos_album_url',
            field=models.URLField(blank=True, default='example.com', max_length=500, verbose_name='Instagram Stories Album URL'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tw_stories_google_photos_album_url',
            field=models.URLField(blank=True, default='example.com', max_length=500, verbose_name='Twitter Stories Album URL'),
        ),
    ]
