# Generated by Django 3.0.7 on 2020-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_stories_google_photos_album_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='stories_fetch_ctrl',
            field=models.BooleanField(default=False, verbose_name='Stories fetched?'),
        ),
    ]
