# Generated by Django 3.0.7 on 2020-07-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20200701_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='stories_fetch_ctrl',
        ),
        migrations.AddField(
            model_name='campaign',
            name='fb_stories_fetch_ctrl',
            field=models.BooleanField(default=False, verbose_name='Facebook Stories fetched?'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='in_stories_fetch_ctrl',
            field=models.BooleanField(default=False, verbose_name='Instagram Stories fetched?'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tw_stories_fetch_ctrl',
            field=models.BooleanField(default=False, verbose_name='Twitter Stories fetched?'),
        ),
    ]
