# Generated by Django 3.0.7 on 2020-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20200701_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name_plural': 'Admin - Campaign'},
        ),
        migrations.AlterModelOptions(
            name='campaignreport',
            options={'verbose_name_plural': 'Campaign Report Data'},
        ),
        migrations.AlterModelOptions(
            name='livecampaign',
            options={'verbose_name_plural': 'Campaign Live Details'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fb_stories_google_photos_album_url',
            field=models.URLField(blank=True, default='http://example.com', max_length=500, verbose_name='Facebook Stories Album URL'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='in_stories_google_photos_album_url',
            field=models.URLField(blank=True, default='http://example.com', max_length=500, verbose_name='Instagram Stories Album URL'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='live_google_sheet',
            field=models.URLField(default='http://example.com', verbose_name='Live Google Sheet'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='particaipating_profiles',
            field=models.IntegerField(default=0, verbose_name='participating profiles'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='reports_google_sheet',
            field=models.URLField(default='http://example.com', verbose_name='Reports Google Sheet'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='slide_url',
            field=models.URLField(default='http://example.com', verbose_name='Slide URL'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tw_stories_google_photos_album_url',
            field=models.URLField(blank=True, default='http://example.com', max_length=500, verbose_name='Twitter Stories Album URL'),
        ),
    ]
