# Generated by Django 3.0.7 on 2020-07-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20200703_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='brand',
        ),
    ]
