# Generated by Django 3.0.8 on 2020-07-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_remove_campaign_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Name'),
        ),
    ]
