# Generated by Django 3.0.8 on 2020-08-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='twitter_collection_url',
            field=models.URLField(blank=True, max_length=1500, null=True, verbose_name='Twitter Posts Collection URL'),
        ),
    ]
