# Generated by Django 3.0.3 on 2020-10-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_twitter_collection_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_module',
            field=models.CharField(choices=[('v1', 'V1'), ('v2', 'V2')], default='v1', max_length=10, verbose_name='Campaign Module'),
        ),
    ]
