# Generated by Django 3.0.3 on 2020-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_campaign_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='cost_per_post_impression',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='post_stats',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='website_traffic',
        ),
        migrations.AddField(
            model_name='campaign',
            name='cost_per_reach',
            field=models.CharField(blank=True, max_length=50, verbose_name='cost per reach'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='post_engagement',
            field=models.IntegerField(default=0, verbose_name='post engagement'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='video_views',
            field=models.IntegerField(default=0, verbose_name='video views'),
        ),
    ]
