# Generated by Django 3.0.3 on 2021-01-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20201027_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='live_fb_posts',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='live_fb_stories',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='live_in_posts',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='live_in_stories',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='live_tw_posts',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='live_tw_stories',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fb_posts',
            field=models.IntegerField(default=0, verbose_name='Target facebook posts'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fb_stories',
            field=models.IntegerField(default=0, verbose_name='Target facebook stories'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='in_posts',
            field=models.IntegerField(default=0, verbose_name='Target instagram posts'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='in_stories',
            field=models.IntegerField(default=0, verbose_name='Target instagram stories'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tw_posts',
            field=models.IntegerField(default=0, verbose_name='Target twitter posts'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tw_stories',
            field=models.IntegerField(default=0, verbose_name='Target twitter stories'),
        ),
    ]
